apiVersion: 1

datasources:
  - name: InfluxDB3-core
    type: influxdb
    access: proxy
    url: http://influxdb3-core:8181
    jsonData:
      httpMode: POST
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Bearer ${INFLUXDB_TOKEN}
    database: ${INFLUXDB_BUCKET}
    isDefault: true
